services:
  - type: web
    name: great-erp
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
